spring.application.name=Portfolio-Backend
# ===============================
# DATABASE CONFIGURATION (NeonDB PostgreSQL)
# ===============================
spring.datasource.url=jdbc:postgresql://${DB_HOST:ep-steep-hall-am0nnlx4-pooler.c-5.us-east-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:neondb}?sslmode=require
spring.datasource.username=${DB_USER:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_5Sojb3tqMRhf}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONNECTION POOL (HikariCP - Default)
# ===============================
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# LOGGING (Optional)
# ===============================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE